[pytest]
markers =
    login: testes de login

    create: testes de criação genéricos
    create_user: testes de criação de usuário
    create_product: testes de criação de produto

    update: testes de atualização genéricos
    update_user: testes de atualização de usuário
    update_product: testes de atualização de produto

    delete: testes de remoção genéricos
    delete_user: testes de remoção de usuário
    delete_product: testes de remoção de produto

    list: testes de listagem genéricos
    list_user: testes de listagem de usuário
    list_product: testes de listagem de produto